'use client';
/**
 * Generate + print cards from (a) enrolled learners or (b) an Excel file.
 * The Excel path is fully isolated AND fully client-side (src/lib/idcards/
 * excel-client.ts, exceljs): the workbook — including any photos pasted
 * directly into a column — is parsed in the browser's memory only. It is
 * never uploaded, never stored, never sent to a server. Records live only
 * in this page's memory; nothing is written to student tables, and no
 * attendance or SMS behaviour is touched.
 */
import React, { useEffect, useMemo, useState } from 'react';
import { Printer, Upload, Trash2, FileSpreadsheet, Users } from 'lucide-react';
import { IdCardSheets, PrintPortal } from './IdCardSheets';
import { IdCardFace } from './IdCardFace';
import { CARD_FIELDS } from '@/lib/idcards/fields';
import { SHEET_PRESETS, defaultPrintMode, type PrintMode, type SheetSpec } from '@/lib/idcards/layout';
import type { CardRecord, IdCardSpec } from '@/lib/idcards/spec';

interface SheetInfo { name: string; hidden: boolean; rowCount: number; headerRow: number; headers: string[]; sample: string[][]; hasImages?: boolean; }
interface Issue { row: number; field: string; severity: 'error' | 'warning'; message: string; }
interface ExRow { row: number; record: CardRecord; status: 'ok' | 'warning' | 'error'; }

/** A soft sanity cap on in-browser reading, not a storage-plan limit (there
 *  is no storage plan any more — nothing leaves the browser). A workbook
 *  with many embedded photos can get large; this just avoids the tab
 *  hanging on something absurd. */
const STORAGE_SAFE_BYTES = 9 * 1024 * 1024;

interface Props {
  spec: IdCardSpec;
  schoolName: string;
  schoolInfo?: { address?: string; phone?: string; email?: string };
  logoUrl?: string;
  onExcelHeaders?: (headers: string[]) => void;
  /** "Generated by DRAIS" on every printed card — Control-Center-only
   *  setting (src/lib/idcards/watermark.ts), fetched once by the parent
   *  page and passed down so the Design and Generate tabs never disagree. */
  showWatermark?: boolean;
}

const pad2 = (n: number) => String(n).padStart(2, '0');
const fmtDmy = (d: Date) => `${pad2(d.getDate())}/${pad2(d.getMonth() + 1)}/${d.getFullYear()}`;

const fmtDate = (v?: string) => {
  if (!v) return '';
  const d = new Date(v);
  return Number.isNaN(d.getTime()) ? v : d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
};

export function IdCardGenerate({ spec, schoolName, schoolInfo, logoUrl, onExcelHeaders, showWatermark = true }: Props) {
  const [source, setSource] = useState<'learners' | 'excel'>('learners');
  // Dates printed on every card that does not bring its own (e.g. from a spreadsheet column).
  const [issueDate, setIssueDate] = useState(() => fmtDmy(new Date()));
  const [validUntil, setValidUntil] = useState(() => `31/12/${new Date().getFullYear()}`);

  // ── printing options ──
  const [preset, setPreset] = useState('A4 portrait');
  const [margin, setMargin] = useState(10);
  const [gap, setGap] = useState(4);
  const [mode, setMode] = useState<PrintMode>(defaultPrintMode(!!spec.back));
  const [cutMarks, setCutMarks] = useState(true);
  const [printTick, setPrintTick] = useState(0);
  useEffect(() => { setMode(defaultPrintMode(!!spec.back)); }, [!!spec.back]);
  const sheet: SheetSpec = { ...SHEET_PRESETS[preset], marginMm: margin, gapMm: gap };

  // ── learners source ──
  const [learners, setLearners] = useState<CardRecord[]>([]);
  const [learnerIds, setLearnerIds] = useState<number[]>([]);
  const [learnersLoading, setLearnersLoading] = useState(false);
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [search, setSearch] = useState('');

  useEffect(() => {
    if (source !== 'learners' || learners.length) return;
    setLearnersLoading(true);
    (async () => {
      try {
        const json = await (await fetch('/api/students/enrolled?status=active')).json();
        const rows = ((json.students || json.data || json.enrolled || []) as any[]);
        setLearnerIds(rows.map((s) => s.id));
        setLearners(rows.map((s) => ({
          full_name: [s.first_name, s.other_name, s.last_name].filter(Boolean).join(' '),
          first_name: s.first_name || '', last_name: s.last_name || '',
          admission_no: s.admission_no || '',
          class: [s.class_name, s.stream_name].filter(Boolean).join(' '),
          gender: s.gender || '', dob: fmtDate(s.date_of_birth), photo_url: s.photo_url || '',
          school: schoolName, academic_year: '', valid_until: '', guardian_phone: '',
        })));
      } catch { /* shown as empty */ }
      setLearnersLoading(false);
    })();
  }, [source, learners.length, schoolName]);

  const filtered = useMemo(() => learners.map((r, i) => ({ r, i })).filter(({ r }) =>
    !search.trim() || `${r.full_name} ${r.admission_no}`.toLowerCase().includes(search.toLowerCase())), [learners, search]);

  // ── excel source — entirely client-side ──
  // The workbook (including any pasted photos) never leaves the browser: no
  // upload, no storage, no server round-trip for the file. It's parsed with
  // exceljs (which, unlike the xlsx package used elsewhere in DRAIS, reads
  // embedded/pasted images out of the .xlsx, not just cell text) directly
  // in memory, and the ArrayBuffer is discarded on unmount / "Discard file".
  // See src/lib/idcards/excel-client.ts for the parsing/extraction logic.
  const [fileBuffer, setFileBuffer] = useState<ArrayBuffer | null>(null);
  const [fileName, setFileName] = useState('');
  const [sheets, setSheets] = useState<SheetInfo[]>([]);
  const [suggested, setSuggested] = useState<Record<string, Record<string, string>>>({});
  const [sheetName, setSheetName] = useState('');
  const [headerRow, setHeaderRow] = useState(1);
  const [mapping, setMapping] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const [exRows, setExRows] = useState<ExRow[]>([]);
  const [issues, setIssues] = useState<Issue[]>([]);
  const [summary, setSummary] = useState<{ total: number; ok: number; warnings: number; errors: number } | null>(null);
  const [truncated, setTruncated] = useState(false);
  const [includeErrors, setIncludeErrors] = useState(false);

  const currentSheet = sheets.find((s) => s.name === sheetName);
  useEffect(() => { if (currentSheet) onExcelHeaders?.(currentSheet.headers.map((h) => `col:${h}`)); }, [currentSheet, onExcelHeaders]);

  const chooseSheet = (name: string, sh: SheetInfo[] = sheets, sg = suggested) => {
    setSheetName(name);
    const info = sh.find((s) => s.name === name);
    setHeaderRow(info?.headerRow ?? 1);
    setMapping(sg[name] ?? {});
    setExRows([]); setIssues([]); setSummary(null);
  };

  const handleFile = async (file: File) => {
    setBusy(true); setErr('');
    try {
      if (file.size > STORAGE_SAFE_BYTES * 6) {
        setErr('That file is quite large for in-browser reading. Remove unused columns/sheets, or reduce photo resolution, and try again.');
        return;
      }
      const buf = await file.arrayBuffer();
      const { inspectWorkbookClient, suggestMapping } = await import('@/lib/idcards/excel-client');
      const { sheets: sh } = await inspectWorkbookClient(buf);
      if (!sh.length) { setErr('No worksheets found in this file'); return; }
      const sg: Record<string, Record<string, string>> = {};
      sh.forEach((s) => { sg[s.name] = suggestMapping(s.headers); });
      setFileBuffer(buf); setFileName(file.name); setSheets(sh); setSuggested(sg);
      const best = [...sh].filter((s) => !s.hidden).sort((a, b) => b.rowCount - a.rowCount)[0] ?? sh[0];
      chooseSheet(best.name, sh, sg);
    } catch (e: any) {
      setErr(e?.message || 'Could not read this file — is it a valid .xlsx/.xls workbook?');
    } finally { setBusy(false); }
  };

  const applyMapping = async () => {
    if (!fileBuffer) return;
    setBusy(true); setErr('');
    try {
      const { extractRowsClient } = await import('@/lib/idcards/excel-client');
      const extraction = await extractRowsClient(fileBuffer, { sheetName, headerRow, mapping, schoolName });
      setExRows(extraction.rows);
      setIssues(extraction.issues);
      setSummary({
        total: extraction.rows.length,
        ok: extraction.rows.filter((r) => r.status === 'ok').length,
        warnings: extraction.rows.filter((r) => r.status === 'warning').length,
        errors: extraction.rows.filter((r) => r.status === 'error').length,
      });
      setTruncated(extraction.truncated);
    } catch (e: any) {
      setErr(e?.message || 'Could not read the sheet');
    } finally { setBusy(false); }
  };

  const discardFile = () => {
    setFileBuffer(null); setSheets([]); setExRows([]); setIssues([]); setSummary(null); setFileName(''); setMapping({});
  };

  // ── records to render ──
  const records: CardRecord[] = useMemo(() => {
    let base: CardRecord[];
    if (source === 'excel') base = exRows.filter((r) => includeErrors || r.status !== 'error').map((r) => r.record);
    else {
      const ids = selected.size ? [...selected] : filtered.map(({ i }) => i);
      base = ids.map((i) => learners[i]).filter(Boolean);
    }
    const year = validUntil.match(/\d{4}/)?.[0] ?? String(new Date().getFullYear());
    // Values the card itself carries win; everything else falls back to the school / print options.
    return base.map((r) => ({
      ...r,
      school: r.school || schoolName,
      school_address: r.school_address || schoolInfo?.address || '',
      school_phone: r.school_phone || schoolInfo?.phone || '',
      school_email: r.school_email || schoolInfo?.email || '',
      academic_year: r.academic_year || year,
      issue_date: r.issue_date || issueDate,
      valid_until: r.valid_until || validUntil,
    }));
  }, [source, exRows, includeErrors, selected, filtered, learners, schoolName, schoolInfo?.address, schoolInfo?.phone, schoolInfo?.email, issueDate, validUntil]);

  const excluded = source === 'excel' && summary ? (includeErrors ? 0 : summary.errors) : 0;

  return (
    <div className="flex flex-col gap-4">
      <PrintPortal trigger={printTick} spec={spec} records={records} logoUrl={logoUrl} sheet={sheet} mode={mode} cutMarks={cutMarks} showWatermark={showWatermark} />
      <div className="flex gap-2">
        <SourceTab on={source === 'learners'} onClick={() => setSource('learners')} icon={<Users className="w-3.5 h-3.5" />}>Enrolled learners</SourceTab>
        <SourceTab on={source === 'excel'} onClick={() => setSource('excel')} icon={<FileSpreadsheet className="w-3.5 h-3.5" />}>Excel file</SourceTab>
      </div>

      {source === 'learners' && (
        <section className={cardCls}>
          <div className="flex gap-2 items-center flex-wrap mb-2">
            <input placeholder="Search name or reg. no" value={search} onChange={(e) => setSearch(e.target.value)} className={`${inputCls} w-60`} />
            <button className={btnCls} onClick={() => setSelected(new Set(filtered.map(({ i }) => i)))}>Select all shown</button>
            <button className={btnCls} onClick={() => setSelected(new Set())}>Clear</button>
            <span className="text-gray-500 dark:text-gray-400 text-xs">{selected.size ? `${selected.size} selected` : `nothing selected — all ${filtered.length} shown will print`}</span>
          </div>
          {learnersLoading && <p className="text-sm text-gray-600 dark:text-gray-300">Loading learners…</p>}
          <div className="max-h-56 overflow-auto border border-gray-200 dark:border-gray-700 rounded-lg">
            {filtered.slice(0, 500).map(({ r, i }) => (
              <label key={learnerIds[i] ?? i} className="flex gap-2 px-2 py-1 border-b border-gray-100 dark:border-gray-800 last:border-0 text-sm items-center hover:bg-gray-50 dark:hover:bg-slate-800/60">
                <input type="checkbox" checked={selected.has(i)} onChange={() => setSelected((p) => { const n = new Set(p); n.has(i) ? n.delete(i) : n.add(i); return n; })} />
                <span className="flex-1 text-gray-900 dark:text-gray-100">{r.full_name}</span>
                <span className="text-gray-500 dark:text-gray-400">{r.admission_no}</span>
                <span className="text-gray-500 dark:text-gray-400">{r.class}</span>
              </label>
            ))}
          </div>
        </section>
      )}

      {source === 'excel' && (
        <section className={cardCls}>
          <div className="p-2 rounded-lg border border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/20 text-green-900 dark:text-green-300 text-xs mb-2.5">
            Cards made from a spreadsheet are for printing only. No learner records are created or changed, and no attendance or SMS activity is triggered.
            The file is read entirely in your browser — it is never uploaded or stored anywhere; closing this page or pressing "Discard file" clears it from memory.
          </div>

          {!fileBuffer && (
            <>
              <label className={`${btnCls} inline-flex items-center gap-1.5 cursor-pointer w-fit`}>
                <Upload className="w-3.5 h-3.5" /> Choose Excel file
                <input type="file" accept=".xlsx,.xls" disabled={busy} className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFile(f); e.target.value = ''; }} />
              </label>
              {busy && <p className="text-xs text-gray-600 dark:text-gray-300 mt-1.5">Reading workbook…</p>}
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1.5">.xlsx or .xls, up to 2000 rows read. Photos pasted or dragged directly into a "Photo"/"Image" column are read automatically; an https:// link in that column also still works.</p>
            </>
          )}
          {err && <p className="text-red-600 dark:text-red-400 text-sm">{err}</p>}

          {fileBuffer && (
            <>
              <div className="flex gap-2 items-center flex-wrap mb-2.5">
                <strong className="text-sm text-gray-900 dark:text-gray-100">{fileName}</strong>
                {currentSheet?.hasImages && <span className="text-xs text-green-600 dark:text-green-400">Pasted photos found on this sheet</span>}
                <button className={`${btnCls} text-red-600 dark:text-red-400 inline-flex items-center gap-1`} onClick={discardFile}><Trash2 className="w-3.5 h-3.5" />Discard file</button>
              </div>

              <div className="flex gap-3 flex-wrap mb-2.5">
                <label className="text-sm text-gray-700 dark:text-gray-300">Worksheet{' '}
                  <select className={inputCls} value={sheetName} onChange={(e) => chooseSheet(e.target.value)}>
                    {sheets.map((s) => <option key={s.name} value={s.name}>{s.name} ({s.rowCount} rows){s.hidden ? ' — hidden' : ''}</option>)}
                  </select>
                </label>
                <label className="text-sm text-gray-700 dark:text-gray-300">Header row{' '}
                  <input type="number" min={1} max={50} className={`${inputCls} w-16`} value={headerRow} onChange={(e) => setHeaderRow(Math.max(1, Number(e.target.value) || 1))} />
                </label>
              </div>

              {currentSheet && currentSheet.headers.length > 0 && (
                <div className="overflow-x-auto mb-2.5">
                  <table className="border-collapse text-xs">
                    <thead><tr>{currentSheet.headers.map((h) => <th key={h} className={thCls}>{h}</th>)}</tr></thead>
                    <tbody>{currentSheet.sample.slice(0, 3).map((r, i) => <tr key={i}>{currentSheet.headers.map((_, c) => <td key={c} className={tdCls}>{r[c]}</td>)}</tr>)}</tbody>
                  </table>
                  <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-1">Sample rows use the suggested header row; press "Read rows" after changing it.</p>
                </div>
              )}

              <div className="grid gap-2 mb-2.5" style={{ gridTemplateColumns: 'repeat(auto-fill,minmax(230px,1fr))' }}>
                {CARD_FIELDS.map((f) => (
                  <label key={f.key} className="text-xs flex flex-col gap-0.5 text-gray-700 dark:text-gray-300">
                    {f.label}{f.key === 'full_name' && <span className="text-red-600 dark:text-red-400"> (required, or map first + last)</span>}
                    <select className={inputCls} value={mapping[f.key] ?? ''} onChange={(e) => setMapping((m) => { const n = { ...m }; if (e.target.value) n[f.key] = e.target.value; else delete n[f.key]; return n; })}>
                      <option value="">— not mapped —</option>
                      {(currentSheet?.headers ?? []).map((h) => <option key={h} value={h}>{h}</option>)}
                    </select>
                  </label>
                ))}
              </div>
              <p className="text-[11px] text-gray-500 dark:text-gray-400 mb-2">Any other column can be used in the design as {'{col:Column Name}'}.</p>
              <button className={primaryCls} disabled={busy} onClick={applyMapping}>{busy ? 'Reading…' : 'Read rows & validate'}</button>

              {summary && (
                <div className="mt-3">
                  <p className="text-sm text-gray-700 dark:text-gray-300">
                    <strong className="text-gray-900 dark:text-gray-100">{summary.total}</strong> rows read — <span className="text-green-700 dark:text-green-400">{summary.ok} ready</span>,{' '}
                    <span className="text-amber-700 dark:text-amber-400">{summary.warnings} with warnings</span>,{' '}
                    <span className="text-red-700 dark:text-red-400">{summary.errors} with errors</span>.
                    {truncated && <span className="text-red-700 dark:text-red-400"> The sheet has more than 2000 rows; only the first 2000 were read.</span>}
                  </p>
                  {summary.errors > 0 && (
                    <label className="text-xs flex items-center gap-1.5 text-gray-700 dark:text-gray-300 mt-1">
                      <input type="checkbox" checked={includeErrors} onChange={(e) => setIncludeErrors(e.target.checked)} /> Print rows with errors too ({excluded ? `${excluded} currently left out` : 'included'})
                    </label>
                  )}
                  {issues.length > 0 && (
                    <div className="max-h-44 overflow-auto border border-gray-200 dark:border-gray-700 rounded-lg mt-1.5">
                      <table className="border-collapse text-xs w-full">
                        <thead><tr><th className={thCls}>Row</th><th className={thCls}>Field</th><th className={thCls}>Level</th><th className={thCls}>Problem</th></tr></thead>
                        <tbody>{issues.slice(0, 300).map((i, k) => (
                          <tr key={k}><td className={tdCls}>{i.row}</td><td className={tdCls}>{i.field}</td>
                            <td className={`${tdCls} ${i.severity === 'error' ? 'text-red-600 dark:text-red-400' : 'text-amber-600 dark:text-amber-400'}`}>{i.severity}</td><td className={tdCls}>{i.message}</td></tr>
                        ))}</tbody>
                      </table>
                      {issues.length > 300 && <p className="text-[11px] p-1.5 text-gray-500 dark:text-gray-400">Showing the first 300 of {issues.length} issues.</p>}
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </section>
      )}

      <section className={cardCls}>
        <h3 className="m-0 mb-2 text-sm font-semibold text-gray-900 dark:text-gray-100">Print layout</h3>
        <div className="flex gap-3 flex-wrap items-center text-sm text-gray-700 dark:text-gray-300">
          <label>Sheet <select className={inputCls} value={preset} onChange={(e) => setPreset(e.target.value)}>{Object.keys(SHEET_PRESETS).map((k) => <option key={k}>{k}</option>)}</select></label>
          <label>Margin mm <input type="number" className={`${inputCls} w-16`} min={0} max={30} value={margin} onChange={(e) => setMargin(Math.max(0, Number(e.target.value) || 0))} /></label>
          <label>Gap mm <input type="number" className={`${inputCls} w-16`} min={0} max={20} value={gap} onChange={(e) => setGap(Math.max(0, Number(e.target.value) || 0))} /></label>
          <label>Mode{' '}
            <select className={inputCls} value={mode} disabled={!spec.back} onChange={(e) => setMode(e.target.value as PrintMode)}>
              {!spec.back && <option value="front_only">Single-sided</option>}
              {spec.back && <option value="side_by_side">Front left, back right (side by side)</option>}
              {spec.back && <option value="duplex_long">Double-sided printer — flip on long edge</option>}
              {spec.back && <option value="duplex_short">Double-sided printer — flip on short edge</option>}
              {spec.back && <option value="front_only">Fronts only</option>}
            </select>
          </label>
          <label className="flex items-center gap-1"><input type="checkbox" checked={cutMarks} onChange={(e) => setCutMarks(e.target.checked)} /> Cut guides</label>
        </div>
        <div className="flex gap-3 flex-wrap items-center text-sm text-gray-700 dark:text-gray-300 mt-2">
          <label>Date of issue <input className={`${inputCls} w-28`} value={issueDate} onChange={(e) => setIssueDate(e.target.value)} /></label>
          <label>Valid until <input className={`${inputCls} w-28`} value={validUntil} onChange={(e) => setValidUntil(e.target.value)} /></label>
          <span className="text-xs text-gray-500 dark:text-gray-400">Printed where the design uses {'{issue_date}'} / {'{valid_until}'}; a spreadsheet column mapped to Valid until takes priority.</span>
        </div>
        {spec.back && mode === 'side_by_side' && (
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
            Each learner's front is printed on the left and the back on the right of the same row, so both faces are always together. Works on any printer — cut out and laminate.
          </p>
        )}
        {spec.back && mode.startsWith('duplex') && (
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
            For printers that print on both sides of the paper: all the fronts are on one page and all the backs on the next, so each back lands behind its own front once the paper is turned. Print double-sided with "flip on {mode === 'duplex_long' ? 'long' : 'short'} edge" — the back pages are already mirrored. Do a one-sheet test on plain paper first; printer feed offsets vary. If your printer cannot print on both sides, use "Front left, back right" instead.
          </p>
        )}
        <div className="mt-2.5 flex gap-3 items-center">
          <button className={`${primaryCls} inline-flex items-center gap-1.5`} disabled={!records.length} onClick={() => setPrintTick((n) => n + 1)}>
            <Printer className="w-4 h-4" /> Print / Save as PDF ({records.length} card{records.length === 1 ? '' : 's'})
          </button>
          {excluded > 0 && <span className="text-xs text-amber-600 dark:text-amber-400">{excluded} row(s) with errors are not included.</span>}
        </div>
      </section>

      {records.length > 0 ? (
        <section className={cardCls}>
          <h3 className="m-0 mb-2 text-sm font-semibold text-gray-900 dark:text-gray-100">Card preview</h3>
          <div className="flex gap-3 flex-wrap mb-3">
            {records.slice(0, 3).map((r, i) => (
              <div key={i} className="flex gap-1.5">
                <IdCardFace spec={spec} face="front" record={r} logoUrl={logoUrl} unit={3.4} showWatermark={showWatermark} />
                {spec.back && <IdCardFace spec={spec} face="back" record={r} logoUrl={logoUrl} unit={3.4} showWatermark={showWatermark} />}
              </div>
            ))}
          </div>
          <h3 className="m-0 mb-2 text-sm font-semibold text-gray-900 dark:text-gray-100">Sheet preview</h3>
          <IdCardSheets spec={spec} records={records} logoUrl={logoUrl} sheet={sheet} mode={mode} cutMarks={cutMarks} previewScale={0.45} showWatermark={showWatermark} />
        </section>
      ) : (
        <p className="text-gray-500 dark:text-gray-400 text-sm">{source === 'excel' ? 'Upload a file, map the columns and press "Read rows" to preview cards.' : 'No learners to print yet.'}</p>
      )}
    </div>
  );
}

function SourceTab({ on, onClick, icon, children }: { on: boolean; onClick: () => void; icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <button onClick={onClick} className={`inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-sm font-semibold border transition-colors ${
      on ? 'bg-gray-900 dark:bg-indigo-600 text-white border-gray-900 dark:border-indigo-600' : 'bg-white dark:bg-slate-800 text-gray-900 dark:text-gray-200 border-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-slate-700'
    }`}>
      {icon}{children}
    </button>
  );
}

const inputCls = 'border border-gray-300 dark:border-gray-600 rounded px-2 py-1 bg-white dark:bg-slate-800 text-gray-900 dark:text-gray-100 text-sm';
const btnCls = 'border border-gray-300 dark:border-gray-600 rounded-lg px-2.5 py-1.5 bg-white dark:bg-slate-800 text-gray-900 dark:text-gray-100 hover:bg-gray-50 dark:hover:bg-slate-700 cursor-pointer text-sm disabled:opacity-50';
const primaryCls = `${btnCls} bg-indigo-600 dark:bg-indigo-600 text-white border-indigo-600 hover:bg-indigo-700 dark:hover:bg-indigo-500 px-4 py-2 text-sm font-medium`;
const cardCls = 'border border-gray-200 dark:border-gray-700 rounded-xl p-3.5 bg-white dark:bg-slate-900 text-gray-900 dark:text-gray-100';
const thCls = 'border border-gray-200 dark:border-gray-700 px-2 py-1 bg-gray-50 dark:bg-slate-800 text-left whitespace-nowrap text-gray-700 dark:text-gray-300';
const tdCls = 'border border-gray-200 dark:border-gray-700 px-2 py-1 whitespace-nowrap max-w-[220px] overflow-hidden text-ellipsis text-gray-700 dark:text-gray-300';
