/**
 * Standardized server-side CSV export (P3).
 *
 * Every DRAIS export produced through this helper carries the same metadata
 * header — a school management platform must never trap institutional data,
 * and an exported file must be self-describing: WHO generated it, from WHICH
 * school, WHEN, and over WHAT scope. Pair with a logAudit(EXPORTED_*) call at
 * the route so every export is also accountable.
 */
import { NextResponse } from 'next/server';

export interface CsvColumn<T> {
  key: string;
  label: string;
  value?: (row: T) => unknown;
}

export interface CsvMeta {
  title: string;                 // e.g. "Audit Log Export"
  schoolName?: string | null;
  generatedBy?: string | null;   // display name / email of the actor
  scope?: string | null;         // human summary of filters applied
}

function esc(v: unknown): string {
  const s = v == null ? '' : String(v);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Build a CSV string: metadata header block, blank line, column headers, rows. */
export function buildCsv<T>(columns: CsvColumn<T>[], rows: T[], meta: CsvMeta): string {
  const lines: string[] = [];
  lines.push(esc(meta.title));
  if (meta.schoolName) lines.push(`School,${esc(meta.schoolName)}`);
  lines.push(`Generated,${esc(new Date().toISOString())}`);
  if (meta.generatedBy) lines.push(`Generated by,${esc(meta.generatedBy)}`);
  if (meta.scope) lines.push(`Scope,${esc(meta.scope)}`);
  lines.push(`Rows,${rows.length}`);
  lines.push('');
  lines.push(columns.map(c => esc(c.label)).join(','));
  for (const r of rows) {
    lines.push(columns.map(c => esc(c.value ? c.value(r) : (r as any)[c.key])).join(','));
  }
  return lines.join('\n');
}

/** Wrap a CSV string in a downloadable NextResponse. */
export function csvResponse(filename: string, csv: string): NextResponse {
  return new NextResponse(csv, {
    headers: {
      'Content-Type': 'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}
