-- ============================================================================
-- Phase 1 — Universal soft-delete columns
--
-- Every table that already has `deleted_at` gains four sibling columns:
--   deleted_by    BIGINT NULL
--   delete_reason VARCHAR(500) NULL
--   restored_at   DATETIME NULL
--   restored_by   BIGINT NULL
--
-- TiDB supports ADD COLUMN IF NOT EXISTS since v4.0 so the migration is
-- idempotent — re-running it is a no-op.
--
-- Rollback per table:
--   ALTER TABLE <table>
--     DROP COLUMN IF EXISTS restored_by,
--     DROP COLUMN IF EXISTS restored_at,
--     DROP COLUMN IF EXISTS delete_reason,
--     DROP COLUMN IF EXISTS deleted_by;
-- ============================================================================

ALTER TABLE academic_years            ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE attendance_sessions       ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE biometric_devices         ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE branches                  ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE class_results             ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE classes                   ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE contacts                  ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE curriculums               ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE departments               ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE device_configs            ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE devices                   ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE documents                 ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE enrollments               ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE exams                     ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE expenditures              ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE feature_flags             ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE manual_attendance_entries ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE marks_migration_policies  ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE notifications             ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE payroll_definitions       ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE people                    ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE promotions                ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE result_types              ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE roles                     ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE salary_payments           ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE school_info               ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE schools                   ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE staff                     ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE streams                   ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE students                  ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE subjects                  ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE tahfiz_results            ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE terms                     ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE users                     ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE villages                  ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE waivers_discounts         ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
ALTER TABLE workplans                 ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL, ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL, ADD COLUMN IF NOT EXISTS restored_at DATETIME NULL, ADD COLUMN IF NOT EXISTS restored_by BIGINT NULL;
