/**
 * Build an ID Card Studio template from a Publisher shape dump.
 *
 *   npx tsx scripts/idcards/build-template.mts <shapes.json> <out.ts> <ExportName> [knownSchoolName]
 *
 * The output holds only the finished design (positions, styling, {tokens}); every sample name, number
 * and phone from the source file has already been replaced by a placeholder.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { importPublisherShapes } from '../../src/lib/idcards/publisher-import.ts';

const [, , dumpPath, outPath, exportName, known] = process.argv;
if (!dumpPath || !outPath || !exportName) {
  console.error('usage: build-template.mts <shapes.json> <out.ts> <ExportName> [knownSchoolName]');
  process.exit(1);
}
const { spec, findings, warnings } = importPublisherShapes(JSON.parse(readFileSync(dumpPath, 'utf8')), { knownSchoolName: known });
const body = `// Generated by scripts/idcards/build-template.mts from a Publisher template — do not edit by hand.
import type { IdCardSpec } from '../spec';

export const ${exportName}: IdCardSpec = ${JSON.stringify(spec, null, 2)};
`;
writeFileSync(outPath, body);
console.log(`Wrote ${outPath}: ${spec.front.elements.length} front + ${spec.back?.elements.length ?? 0} back elements, ${findings.length} placeholders`);
warnings.forEach((w) => console.log('warning:', w));
