'use client';

/**
 * Control Center — "Generated by DRAIS" ID card watermark.
 * On by default for every school; can only be turned off here, per school,
 * as a one-off exception a school asked for directly.
 */
import React from 'react';
import useSWR from 'swr';
import { BadgeCheck, Loader2 } from 'lucide-react';

const fetcher = (u: string) => fetch(u, { cache: 'no-store' }).then((r) => r.json());

export default function WatermarkControlPage() {
  const { data, isLoading, mutate } = useSWR<any>('/api/control-center/id-cards/watermark', fetcher);
  const [busyId, setBusyId] = React.useState<number | null>(null);

  const toggle = async (schoolId: number, disabled: boolean) => {
    setBusyId(schoolId);
    try {
      await fetch('/api/control-center/id-cards/watermark', {
        method: 'PUT', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ schoolId, disabled }),
      });
      await mutate();
    } finally { setBusyId(null); }
  };

  const schools: any[] = data?.schools || [];
  const canManage = !!data?.canManage;

  return (
    <div className="space-y-4">
      <div className="flex items-start gap-3">
        <BadgeCheck className="w-5 h-5 text-indigo-400 mt-0.5" />
        <div>
          <h1 className="text-sm font-semibold text-slate-100">ID card watermark</h1>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl">
            "Generated by DRAIS" prints on every ID card, on by default. There is no school-facing way to turn it
            off — a school that wants it removed has to ask directly, and you disable it for them here, one school
            at a time. Turning it back on removes the exception entirely.
          </p>
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-700/60 rounded-xl overflow-hidden">
        {isLoading ? (
          <div className="p-6 flex items-center gap-2 text-sm text-slate-400"><Loader2 className="w-4 h-4 animate-spin" /> Loading schools…</div>
        ) : (
          <table className="w-full text-sm">
            <thead className="bg-slate-800/60 text-slate-400 text-xs uppercase tracking-wide">
              <tr><th className="text-left px-4 py-2 font-medium">School</th><th className="text-left px-4 py-2 font-medium">Watermark</th><th className="px-4 py-2" /></tr>
            </thead>
            <tbody className="divide-y divide-slate-800">
              {schools.map((s) => (
                <tr key={s.id} className="hover:bg-slate-800/40">
                  <td className="px-4 py-2 text-slate-200">{s.name}</td>
                  <td className="px-4 py-2">
                    <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${s.watermarkEnabled ? 'bg-emerald-900/40 text-emerald-300' : 'bg-amber-900/40 text-amber-300'}`}>
                      {s.watermarkEnabled ? 'On (default)' : 'Off (exception)'}
                    </span>
                  </td>
                  <td className="px-4 py-2 text-right">
                    <button
                      disabled={!canManage || busyId === s.id}
                      onClick={() => toggle(s.id, s.watermarkEnabled)}
                      className="text-xs px-3 py-1.5 rounded-lg border border-slate-600 text-slate-200 hover:bg-slate-800 disabled:opacity-40"
                    >
                      {busyId === s.id ? 'Saving…' : s.watermarkEnabled ? 'Turn off for this school' : 'Turn back on'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
      {!canManage && <p className="text-xs text-amber-400">Your role can view this but not change it.</p>}
    </div>
  );
}
