/**
 * "Generated by DRAIS" watermark on printed ID cards — on by default for
 * every school, and can ONLY be turned off from Control Center (not from
 * any school-facing settings page). A school that wants it removed has to
 * ask Xhenvolt directly; there is deliberately no self-service toggle.
 *
 * Rendered as a fixed overlay in IdCardFace.tsx, NOT as an element in
 * IdCardSpec — it's not part of a design a school can select, move or
 * delete in the Studio.
 *
 * Stored as a single per-school override in school_settings (matching the
 * quiet-hours / logs-density pattern) — absence of a row means enabled
 * (the default); a row only ever represents an explicit, founder-approved
 * exception.
 */
import { query } from '@/lib/db';

const KEY = 'idcards.watermark_disabled';

export async function isWatermarkEnabled(schoolId: number): Promise<boolean> {
  try {
    const rows = (await query(
      `SELECT value_text FROM school_settings WHERE school_id = ? AND key_name = ? LIMIT 1`,
      [schoolId, KEY],
    )) as Array<{ value_text: string | null }>;
    return rows[0]?.value_text !== '1';
  } catch {
    return true; // fail safe: the watermark stays on if the setting can't be read
  }
}

export async function setWatermarkDisabled(schoolId: number, disabled: boolean): Promise<void> {
  const existing = (await query(
    `SELECT id FROM school_settings WHERE school_id = ? AND key_name = ? LIMIT 1`,
    [schoolId, KEY],
  )) as Array<{ id: number }>;
  if (disabled) {
    if (existing[0]) await query(`UPDATE school_settings SET value_text = '1' WHERE id = ?`, [existing[0].id]);
    else await query(`INSERT INTO school_settings (school_id, key_name, value_text) VALUES (?, ?, '1')`, [schoolId, KEY]);
  } else if (existing[0]) {
    // Re-enabling removes the one-time exception entirely — back to the default.
    await query(`DELETE FROM school_settings WHERE id = ?`, [existing[0].id]);
  }
}
