/**
 * "Generated by DRAIS" watermark on printed ID cards — on by default for
 * every school, and can ONLY be turned off from Control Center (not from
 * any school-facing settings page). A school that wants it removed has to
 * ask Xhenvolt directly; there is deliberately no self-service toggle.
 *
 * Rendered as a fixed overlay in IdCardFace.tsx, NOT as an element in
 * IdCardSpec — it's not part of a design a school can select, move or
 * delete in the Studio.
 *
 * Stored as a single per-school override in school_settings (matching the
 * quiet-hours / logs-density pattern) — absence of a row means enabled
 * (the default); a row only ever represents an explicit, founder-approved
 * exception.
 */
import { query } from '@/lib/db';
import { getDbMode } from '@/lib/db/db-mode';

const KEY = 'idcards.watermark_disabled';

/**
 * local-sqlite branch — Phase 7 sub-effort 37. query() throws in this mode
 * (pools.ts), which this file's own try/catch previously swallowed into
 * the fail-safe "watermark stays on" default — SAFE, but not CORRECT: a
 * school's real Control-Center override (a genuine school_settings row,
 * already copied offline like any other school-scoped setting) was being
 * silently ignored rather than honored. Branched properly instead of
 * leaving it to the catch-all.
 */
export async function isWatermarkEnabled(schoolId: number): Promise<boolean> {
  if (getDbMode() === 'local-sqlite') {
    const { getSqliteDb } = await import('@/lib/repo/sqlite/singleton');
    const db = getSqliteDb();
    const row = db.prepare(`SELECT value_text FROM school_settings WHERE school_id = ? AND key_name = ? LIMIT 1`).get(schoolId, KEY) as { value_text: string | null } | undefined;
    return row?.value_text !== '1';
  }
  try {
    const rows = (await query(
      `SELECT value_text FROM school_settings WHERE school_id = ? AND key_name = ? LIMIT 1`,
      [schoolId, KEY],
    )) as Array<{ value_text: string | null }>;
    return rows[0]?.value_text !== '1';
  } catch {
    return true; // fail safe: the watermark stays on if the setting can't be read
  }
}

export async function setWatermarkDisabled(schoolId: number, disabled: boolean): Promise<void> {
  if (getDbMode() === 'local-sqlite') {
    const { getSqliteDb } = await import('@/lib/repo/sqlite/singleton');
    const db = getSqliteDb();
    const existing = db.prepare(`SELECT id FROM school_settings WHERE school_id = ? AND key_name = ? LIMIT 1`).get(schoolId, KEY) as { id: number } | undefined;
    if (disabled) {
      if (existing) db.prepare(`UPDATE school_settings SET value_text = '1' WHERE id = ?`).run(existing.id);
      else db.prepare(`INSERT INTO school_settings (school_id, key_name, value_text) VALUES (?, ?, '1')`).run(schoolId, KEY);
    } else if (existing) {
      db.prepare(`DELETE FROM school_settings WHERE id = ?`).run(existing.id);
    }
    return;
  }

  const existing = (await query(
    `SELECT id FROM school_settings WHERE school_id = ? AND key_name = ? LIMIT 1`,
    [schoolId, KEY],
  )) as Array<{ id: number }>;
  if (disabled) {
    if (existing[0]) await query(`UPDATE school_settings SET value_text = '1' WHERE id = ?`, [existing[0].id]);
    else await query(`INSERT INTO school_settings (school_id, key_name, value_text) VALUES (?, ?, '1')`, [schoolId, KEY]);
  } else if (existing[0]) {
    // Re-enabling removes the one-time exception entirely — back to the default.
    await query(`DELETE FROM school_settings WHERE id = ?`, [existing[0].id]);
  }
}
