/**
 * GET /api/id-cards/watermark-status — read-only. Whether this school's
 * printed ID cards carry the "Generated by DRAIS" watermark right now.
 * There is no PUT here on purpose: this setting can only be changed from
 * Control Center (see /api/control-center/id-cards/watermark).
 */
import { NextRequest, NextResponse } from 'next/server';
import { getSessionSchoolId } from '@/lib/auth';
import { isWatermarkEnabled } from '@/lib/idcards/watermark';

export const runtime = 'nodejs';

export async function GET(req: NextRequest) {
  const session = await getSessionSchoolId(req);
  if (!session) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  const enabled = await isWatermarkEnabled(session.schoolId);
  return NextResponse.json({ success: true, enabled });
}
