/**
 * Control Center — "Generated by DRAIS" ID card watermark, per school.
 *   GET → every school + whether the watermark is currently enabled.
 *   PUT { schoolId, disabled } → turn it off (a founder-approved, one-off
 *        exception a school asked for) or back on.
 *
 * This is deliberately the ONLY place this setting can be changed — there
 * is no school-facing equivalent. Control-session gated and audited.
 */
import { NextRequest, NextResponse } from 'next/server';
import { getControlSession, controlAudit, clientIp } from '@/lib/control/auth';
import { controlCan } from '@/lib/control/permissions';
import { query } from '@/lib/control/db';
import { setWatermarkDisabled } from '@/lib/idcards/watermark';

export const runtime = 'nodejs';

export async function GET(req: NextRequest) {
  const user = await getControlSession(req);
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  if (!controlCan(user.role, 'platform.view')) return NextResponse.json({ error: 'You do not have permission to view this' }, { status: 403 });

  const [schools, overrides] = await Promise.all([
    query(`SELECT id, name FROM schools WHERE deleted_at IS NULL ORDER BY name ASC`, []).catch(() => []) as Promise<any[]>,
    query(`SELECT school_id FROM school_settings WHERE key_name = 'idcards.watermark_disabled' AND value_text = '1'`, []).catch(() => []) as Promise<any[]>,
  ]);
  const disabledSet = new Set(overrides.map((r) => Number(r.school_id)));

  return NextResponse.json({
    success: true,
    canManage: controlCan(user.role, 'schools.manage'),
    schools: schools.map((s) => ({ id: Number(s.id), name: s.name, watermarkEnabled: !disabledSet.has(Number(s.id)) })),
  });
}

export async function PUT(req: NextRequest) {
  const user = await getControlSession(req);
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  if (!controlCan(user.role, 'schools.manage')) return NextResponse.json({ error: 'You do not have permission to change this' }, { status: 403 });

  const body = await req.json().catch(() => null) as any;
  const schoolId = Number(body?.schoolId);
  if (!Number.isInteger(schoolId) || schoolId <= 0) return NextResponse.json({ error: 'schoolId is required' }, { status: 400 });
  const disabled = Boolean(body?.disabled);

  const school = ((await query(`SELECT id, name FROM schools WHERE id = ? AND deleted_at IS NULL LIMIT 1`, [schoolId]).catch(() => [])) as any[])[0];
  if (!school) return NextResponse.json({ error: 'School not found' }, { status: 404 });

  await setWatermarkDisabled(schoolId, disabled);
  await controlAudit(
    user.id, disabled ? 'disable_idcard_watermark' : 'enable_idcard_watermark', `school:${schoolId}`,
    { schoolName: school.name }, clientIp(req),
  ).catch(() => {});

  return NextResponse.json({ success: true, schoolId, watermarkEnabled: !disabled });
}
